spring:
  datasource:
    url: jdbc:h2:mem:lcadb
    username: admin
    password: admin
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /api/docs
    disable-swagger-default-url: true
security:
  jwt:
    secret-key: 7f5f1737c18b668d4a9364a7a2537b0d568b0e2c87a61551c8fca8e95afb4f13
    expiration-time: 3600000